theme: jekyll-theme-cayman
title: [Scouts NSW - North Coast Region Hikes]
description: [A selection of hikes around North Coast NSW suitable for members of the Scout organisation]
github:
    is_project_page: false
